import { Recipe } from '../types';

export const STARTER_RECIPES: Recipe[] = [
  // FRÜHSTÜCK / BREAKFAST
  {
    id: 'rec-bf-1',
    title: 'Protein-Haferflocken mit Beeren & Leinsamen',
    meal_type: 'breakfast_lunchbox',
    prep_time_minutes: 8,
    cook_time_minutes: 0,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 420,
    base_protein_g: 28,
    base_carbs_g: 52,
    base_fat_g: 10,
    allergens: ['Gluten', 'Milch'],
    diet_types: ['vegetarian', 'high_protein'],
    tags: ['Frühstück', 'Ballaststoffe', 'Schnell', 'BioBio'],
    image_url: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=800',
    ingredients: [
      { name: 'Zarte Haferflocken', base_amount: 60, unit: 'g', category: 'Vollkorn & Getreide', matched_offer_retailer: 'Netto', matched_offer_price: 0.79 },
      { name: 'Magerquark oder Skyr', base_amount: 150, unit: 'g', category: 'Molkereiprodukte', matched_offer_retailer: 'NP', matched_offer_price: 0.99 },
      { name: 'Frische Blaubeeren oder TK-Beeren', base_amount: 80, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Lidl', matched_offer_price: 1.49 },
      { name: 'Geschrotete Leinsamen', base_amount: 15, unit: 'g', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Aldi Nord', matched_offer_price: 0.99 },
      { name: 'Zimt & Spritzer Honig', base_amount: 10, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.20 },
    ],
    instructions: [
      'Haferflocken mit etwas heißem Wasser oder Milch 3 Minuten quellen lassen.',
      'Magerquark unterrühren bis eine cremige Konsistenz entsteht.',
      'Mit frischen Beeren, Leinsamen und etwas Zimt toppen. Lässt sich perfekt im Schraubglas mitnehmen.',
    ],
    detailed_instructions: {
      prep_steps: ['Zutaten abwiegen', 'Beeren waschen'],
      cooking_steps: ['Haferflocken quellen lassen', 'Magerquark untermischen'],
      lunchbox_tips: ['Am Vorabend als Overnight Oats im Schraubglas kaltstellen'],
    },
  },
  {
    id: 'rec-bf-2',
    title: 'Vollkorn-Rührei mit Tomaten & Schnittlauch',
    meal_type: 'breakfast_lunchbox',
    prep_time_minutes: 10,
    cook_time_minutes: 5,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 440,
    base_protein_g: 26,
    base_carbs_g: 38,
    base_fat_g: 18,
    allergens: ['Ei', 'Gluten', 'Milch'],
    diet_types: ['vegetarian', 'high_protein'],
    tags: ['Frühstück', 'Warm', 'Klassiker', 'GUT&GÜNSTIG'],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    ingredients: [
      { name: 'Bio Freilandeier', base_amount: 2, unit: 'Stück', category: 'Proteinquellen', matched_offer_retailer: 'Netto', matched_offer_price: 0.50 },
      { name: 'Vollkornbrot', base_amount: 70, unit: 'g', category: 'Vollkorn & Getreide', matched_offer_retailer: 'NP', matched_offer_price: 0.69 },
      { name: 'Kirschtomaten', base_amount: 80, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Lidl', matched_offer_price: 0.89 },
      { name: 'Olivenöl', base_amount: 8, unit: 'ml', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.15 },
      { name: 'Schnittlauch & Pfeffer', base_amount: 5, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.10 },
    ],
    instructions: [
      'Eier in einer Schale verquirlen, mit Prise Salz und Pfeffer würzen.',
      'Pfanne mit etwas Olivenöl erhitzen, Eier auf mittlerer Stufe stocken lassen.',
      'Kirschtomaten halbieren und kurz mitschwenken.',
      'Mit frischem Vollkornbrot und Schnittlauch servieren.',
    ],
  },
  {
    id: 'rec-bf-3',
    title: 'Apfel-Zimt Porridge mit Walnüssen',
    meal_type: 'breakfast_lunchbox',
    prep_time_minutes: 8,
    cook_time_minutes: 4,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 390,
    base_protein_g: 14,
    base_carbs_g: 58,
    base_fat_g: 11,
    allergens: ['Gluten', 'Schalenfrüchte'],
    diet_types: ['vegan', 'vegetarian'],
    tags: ['Frühstück', 'Vegan', 'Wärmend', 'BioBio'],
    image_url: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800',
    ingredients: [
      { name: 'Haferflocken', base_amount: 60, unit: 'g', category: 'Vollkorn & Getreide', matched_offer_retailer: 'Netto', matched_offer_price: 0.79 },
      { name: 'Deutscher Apfel', base_amount: 1, unit: 'Stück', category: 'Obst & Gemüse', matched_offer_retailer: 'Aldi Süd', matched_offer_price: 0.45 },
      { name: 'Walnusskerne', base_amount: 20, unit: 'g', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Rewe', matched_offer_price: 0.89 },
      { name: 'Zimt & Prise Muskat', base_amount: 2, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.10 },
    ],
    instructions: [
      'Haferflocken mit Wasser oder Haferdrink aufkochen.',
      'Apfel würfeln und die Hälfte direkt im Brei weich dünsten.',
      'Mit restlichen Apfelstücken, Walnüssen und reichlich Zimt anrichten.',
    ],
  },

  // MITTAGESSEN / LUNCH
  {
    id: 'rec-lu-1',
    title: 'Bunter Kichererbsen-Bowl mit Feta & Avocado',
    meal_type: 'lunch_lunchbox',
    prep_time_minutes: 12,
    cook_time_minutes: 0,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 520,
    base_protein_g: 24,
    base_carbs_g: 48,
    base_fat_g: 22,
    allergens: ['Milch'],
    diet_types: ['vegetarian', 'high_protein'],
    tags: ['Mittag', 'Lunchbox', 'Meal-Prep', 'Frischetheke'],
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    ingredients: [
      { name: 'Kichererbsen (Dose)', base_amount: 150, unit: 'g', category: 'Hülsenfrüchte', matched_offer_retailer: 'Netto', matched_offer_price: 0.89 },
      { name: 'Feta g.U.', base_amount: 50, unit: 'g', category: 'Molkereiprodukte', matched_offer_retailer: 'Lidl', matched_offer_price: 1.29 },
      { name: 'Gurke & Kirschtomaten', base_amount: 120, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'NP', matched_offer_price: 0.99 },
      { name: 'Avocado', base_amount: 0.5, unit: 'Stück', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Aldi Nord', matched_offer_price: 0.79 },
      { name: 'Zitronen-Kräuter-Dressing', base_amount: 20, unit: 'ml', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.25 },
    ],
    instructions: [
      'Kichererbsen abbrausen und abtropfen lassen.',
      'Gurke und Tomaten mundgerecht schneiden.',
      'Alles in die Lunchbox füllen, Feta darüber bröseln und Avocado auflegen.',
      'Dressing separat oder direkt daruntermischen.',
    ],
  },
  {
    id: 'rec-lu-2',
    title: 'Hähnchenbrust-Wrap mit Paprika & Kräuterquark',
    meal_type: 'lunch_lunchbox',
    prep_time_minutes: 15,
    cook_time_minutes: 8,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 510,
    base_protein_g: 38,
    base_carbs_g: 44,
    base_fat_g: 14,
    allergens: ['Gluten', 'Milch'],
    diet_types: ['high_protein'],
    tags: ['Mittag', 'High-Protein', 'Unterwegs', 'BioBio'],
    image_url: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
    ingredients: [
      { name: 'Hähnchenbrustfilet frisch', base_amount: 130, unit: 'g', category: 'Proteinquellen', matched_offer_retailer: 'Netto', matched_offer_price: 2.19 },
      { name: 'Vollkorn-Tortilla Wraps', base_amount: 1, unit: 'Stück', category: 'Vollkorn & Getreide', matched_offer_retailer: 'Rewe', matched_offer_price: 0.49 },
      { name: 'Bunte Paprika', base_amount: 80, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'NP', matched_offer_price: 0.79 },
      { name: 'Kräuterquark leicht', base_amount: 40, unit: 'g', category: 'Molkereiprodukte', matched_offer_retailer: 'Lidl', matched_offer_price: 0.49 },
    ],
    instructions: [
      'Hähnchenbrust in Streifen schneiden und in der Pfanne scharf anbraten.',
      'Paprika in feine Streifen schneiden.',
      'Wrap mit Kräuterquark bestreichen, Hähnchen und Gemüse auflegen, fest einrollen.',
    ],
  },
  {
    id: 'rec-lu-3',
    title: 'Linsen-Gemüse-Eintopf mit Kartoffeln',
    meal_type: 'lunch_lunchbox',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 460,
    base_protein_g: 22,
    base_carbs_g: 65,
    base_fat_g: 7,
    allergens: ['Sellerie'],
    diet_types: ['vegan', 'vegetarian'],
    tags: ['Mittag', 'Suppe', 'Sättigend', 'Sparpreis'],
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    ingredients: [
      { name: 'Braune Tellerlinsen', base_amount: 70, unit: 'g', category: 'Hülsenfrüchte', matched_offer_retailer: 'Netto', matched_offer_price: 0.59 },
      { name: 'Festkochende Kartoffeln', base_amount: 150, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Aldi Süd', matched_offer_price: 0.49 },
      { name: 'Suppengrün (Möhre, Lauch, Sellerie)', base_amount: 100, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'NP', matched_offer_price: 0.79 },
      { name: 'Gemüsebrühe & Majoran', base_amount: 300, unit: 'ml', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.20 },
    ],
    instructions: [
      'Gemüse und Kartoffeln würfeln.',
      'Linsen mit Gemüsebrühe und Gemüse 20 Minuten gar köcheln.',
      'Mit Schuss Essig und Majoran abschmecken.',
    ],
  },

  // ABENDESSEN / DINNER (GEMEINSAM AM TISCH)
  {
    id: 'rec-di-1',
    title: 'Ofen-Lachsfilet auf Brokkoli-Süßkartoffelbett',
    meal_type: 'dinner_home',
    prep_time_minutes: 15,
    cook_time_minutes: 22,
    difficulty: 'Einfach',
    lunchbox_ready: false,
    base_calories: 580,
    base_protein_g: 42,
    base_carbs_g: 45,
    base_fat_g: 20,
    allergens: ['Fisch'],
    diet_types: ['pescetarian', 'high_protein'],
    tags: ['Abendessen', 'Ofengericht', 'Omega-3', 'Familienessen'],
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    ingredients: [
      { name: 'Frisches Lachsfilet', base_amount: 160, unit: 'g', category: 'Proteinquellen', matched_offer_retailer: 'NP', matched_offer_price: 3.49 },
      { name: 'Frischer Brokkoli', base_amount: 180, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Netto', matched_offer_price: 0.99 },
      { name: 'Süßkartoffel', base_amount: 150, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Lidl', matched_offer_price: 0.89 },
      { name: 'Natives Olivenöl', base_amount: 10, unit: 'ml', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.25 },
      { name: 'Zitrone, Meersalz & Rosmarin', base_amount: 10, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.20 },
    ],
    instructions: [
      'Backofen auf 200°C Ober-/Unterhitze vorheizen.',
      'Süßkartoffeln schälen und in Spalten schneiden, Brokkoli in Röschen teilen.',
      'Gemüse mit Olivenöl, Salz und Rosmarin auf das Backblech geben und 10 Minuten vorbacken.',
      'Lachsfilet mit Zitronensaft beträufeln, salzen und mittig auf das Gemüse legen.',
      'Weitere 12-14 Minuten backen, bis der Lachs saftig rosa gegart ist.',
    ],
  },
  {
    id: 'rec-di-2',
    title: 'Cremige Vollkorn-Pasta mit Blattspinat & Walnüssen',
    meal_type: 'dinner_home',
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 540,
    base_protein_g: 22,
    base_carbs_g: 68,
    base_fat_g: 18,
    allergens: ['Gluten', 'Milch', 'Schalenfrüchte'],
    diet_types: ['vegetarian'],
    tags: ['Abendessen', 'Pasta', 'Schnell', 'Kinderfreundlich'],
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=800',
    ingredients: [
      { name: 'Vollkorn Penne', base_amount: 90, unit: 'g', category: 'Vollkorn & Getreide', matched_offer_retailer: 'Netto', matched_offer_price: 0.79 },
      { name: 'Frischer Baby-Blattspinat', base_amount: 100, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Rewe', matched_offer_price: 1.19 },
      { name: 'Frischkäse natur (Balance)', base_amount: 50, unit: 'g', category: 'Molkereiprodukte', matched_offer_retailer: 'NP', matched_offer_price: 0.69 },
      { name: 'Walnüsse grob gehackt', base_amount: 20, unit: 'g', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Lidl', matched_offer_price: 0.89 },
      { name: 'Knoblauchzehe & Muskat', base_amount: 5, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.10 },
    ],
    instructions: [
      'Vollkorn-Pasta nach Packungsanweisung in Salzwasser al dente kochen, 50ml Pastawasser auffangen.',
      'Knoblauch in etwas Olivenöl andünsten, Spinat zugeben bis er zusammenfällt.',
      'Frischkäse und etwas Pastawasser einrühren, mit Muskat, Salz und Pfeffer abschmecken.',
      'Nudeln unterheben und mit gerösteten Walnüssen bestreuen.',
    ],
  },
  {
    id: 'rec-di-3',
    title: 'Bunte Hähnchen-Wokpfanne mit Brokkoli & Cashews',
    meal_type: 'dinner_home',
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 530,
    base_protein_g: 44,
    base_carbs_g: 36,
    base_fat_g: 17,
    allergens: ['Soja', 'Schalenfrüchte'],
    diet_types: ['high_protein', 'no_pork'],
    tags: ['Abendessen', 'Wok', 'High-Protein', 'Frisch'],
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    ingredients: [
      { name: 'Hähnchenbrustfilet', base_amount: 150, unit: 'g', category: 'Proteinquellen', matched_offer_retailer: 'Netto', matched_offer_price: 2.39 },
      { name: 'Brokkoli & Paprika', base_amount: 160, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'NP', matched_offer_price: 1.29 },
      { name: 'Basmatireis oder Naturreis', base_amount: 50, unit: 'g', category: 'Vollkorn & Getreide', matched_offer_retailer: 'Aldi Süd', matched_offer_price: 0.59 },
      { name: 'Sojasauce & Sesamöl', base_amount: 15, unit: 'ml', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.30 },
      { name: 'Cashewkerne', base_amount: 15, unit: 'g', category: 'Gesunde Fette & Nüsse', matched_offer_retailer: 'Lidl', matched_offer_price: 0.69 },
    ],
    instructions: [
      'Reis aufsetzen und gar kochen.',
      'Hähnchenstreifen im Wok oder Pfanne heiß anbraten und herausnehmen.',
      'Gemüse knackig braten, Hähnchen wieder zufügen, mit Sojasauce ablöschen.',
      'Mit Cashews bestreut servieren.',
    ],
  },
  {
    id: 'rec-di-4',
    title: 'Vegane Süßkartoffel-Kichererbsen-Curry',
    meal_type: 'dinner_home',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    difficulty: 'Einfach',
    lunchbox_ready: true,
    base_calories: 510,
    base_protein_g: 18,
    base_carbs_g: 72,
    base_fat_g: 14,
    allergens: [],
    diet_types: ['vegan', 'vegetarian'],
    tags: ['Abendessen', 'Curry', 'Vegan', 'Meal-Prep'],
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    ingredients: [
      { name: 'Süßkartoffel', base_amount: 150, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Netto', matched_offer_price: 0.89 },
      { name: 'Kichererbsen', base_amount: 120, unit: 'g', category: 'Hülsenfrüchte', matched_offer_retailer: 'NP', matched_offer_price: 0.79 },
      { name: 'Kokosmilch leicht', base_amount: 100, unit: 'ml', category: 'Molkereiprodukte', matched_offer_retailer: 'Rewe', matched_offer_price: 0.99 },
      { name: 'Blattspinat', base_amount: 80, unit: 'g', category: 'Obst & Gemüse', matched_offer_retailer: 'Lidl', matched_offer_price: 0.79 },
      { name: 'Gelbe Currypaste & Ingwer', base_amount: 15, unit: 'g', category: 'Gewürze', matched_offer_retailer: 'Vorratskammer', matched_offer_price: 0.35 },
    ],
    instructions: [
      'Currypaste mit etwas Kokosmilch anrösten.',
      'Gewürfelte Süßkartoffeln und restliche Kokosmilch zugeben, 12 Min. köcheln.',
      'Kichererbsen und Spinat unterrühren, bis der Spinat zusammenfällt.',
    ],
  },
];
